server:
  port: 8082


spring:
  rabbitmq:
    host: 192.168.50.101
    port: 5673
    username: qdsg_2022
    password: qdsg_2022@
    virtual-host: /
    publisher-confirms: true
    #    ublisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        max-concurrency: 5
        concurrency: 5
        acknowledge-mode: manual