mode:
  type: Standalone
  repository:
    type: File
  overwrite: false

spring:
  shardingsphere:
    datasource:
      names: ds-2020,ds-2021,ds-2022
      ds-2020:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/datasource_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 1qaz2wsx
      ds-2021:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/datasource_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 1qaz2wsx
      ds-2022:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/datasource_2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 1qaz2wsx
    rules:
      sharding:
        tables:
          t_order:
            actualDataNodes: ds_${2021..2022}.t_order_${0..2}
            tableStrategy:
              standard:
                shardingColumn: order_id
                shardingAlgorithmName: t-order-inline
            keyGenerateStrategy:
              column: order_id
              keyGeneratorName: snowflake
          t_order_item:
            actualDataNodes: ds_${0..1}.t_order_item_${0..1}
            tableStrategy:
              standard:
                shardingColumn: order_id
                shardingAlgorithmName: t_order-item-inline
            keyGenerateStrategy:
              column: order_item_id
              keyGeneratorName: snowflake
          t_account:
            actualDataNodes: ds_${0..1}.t_account_${0..1}
            tableStrategy:
              standard:
                shardingAlgorithmName: t-account-inline
            keyGenerateStrategy:
              column: account_id
              keyGeneratorName: snowflake
        defaultShardingColumn: account_id
        bindingTables:
          - t_order,t_order_item
        broadcastTables:
          - t_address
        defaultDatabaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: database-inline
        defaultTableStrategy:
          none:
        shardingAlgorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds_${user_id % 3} #database策略 ds_? 数据库后缀策略选择
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_${order_id % 3} #table策略 tb_order_？数据库表后缀策略选择
          t_order-item-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_item_${order_id % 2}
          t-account-inline:
            type: INLINE
            props:
              algorithm-expression: t_account_${account_id % 2}
    #      keyGenerators:
    #        snowflake:
    #          type: SNOWFLAKE

    props:
      sql-show: true