server:
  port: 8081

spring:
  shardingsphere:
    mode:
      type: Memory
  profiles:
    active: dev
  application:
    name: sharding-sphere-demo
  main:
    allow-bean-definition-overriding: true
#  datasource:
#      type: com.zaxxer.hikari.HikariDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      jdbcUrl: jdbc:mysql://localhost:3306/datasource_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: 1qaz2wsx



# actuator  相关
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
#        include: prometheus
#        include: "*"
    health:
      show-details: always
  health:
    diskspace:
      enabled: false



# Logger Config
logging:
  level:
    com.clearvision.shardingspheresample: debug

mybatis-plus:
  mapper-locations=classpath:mapper/*.xml: