spring:
  application:
    name: mybatis-plus-demo
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#      eager: true
#      web-context-unify: true
  clickhouse:
    jdbc:
      url: jdbc:clickhouse://localhost:8023/helloworld
      username:
      password:
      socketTimeout: 600000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.20.186:33061/dp_base?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: dp_app_master
    password: qdsg2021
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081

# actuator  相关
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
#        include: prometheus
#        include: "*"
    health:
      show-details: always
  health:
    diskspace:
      enabled: false



# Logger Config
logging:
  level:
    com.cv.mybatissample: debug

